### ISSUE TITLE
Exception:  'Too many open files'

### ISSUE THREAD

**Issue by Lir10** [olucurious/PyFCM#119]
Hi,

Sometimes i get this exception and it wont stop untill i restart the service.

```
--- <exception caught here> ---
File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1099, in _inlineCallbacks
result = g.send(result)
File "/usr/share/test/test.py", line 706, in handle_received_msg
result = push_service.notify_multiple_devices(registration_ids=google_tokens, data_message=data)
File "/usr/local/lib/python2.7/dist-packages/pyfcm/fcm.py", line 197, in notify_multiple_devices
self.send_request([payload])
File "/usr/local/lib/python2.7/dist-packages/pyfcm/baseapi.py", line 174, in send_request
response = requests.post(self.FCM_END_POINT, headers=self.request_headers(), data=payload)
File "/usr/lib/python2.7/dist-packages/requests/api.py", line 94, in post
return request('post', url, data=data, json=json, **kwargs)
File "/usr/lib/python2.7/dist-packages/requests/api.py", line 49, in request
return session.request(method=method, url=url, **kwargs)
File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
resp = self.send(prep, **send_kwargs)
File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 569, in send
r = adapter.send(request, **kwargs)
File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 407, in send
raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(24, 'Too many open files'))

```

**Comment by Lir10** [comment]
I've upgraded to the latest version of pyfcm i'll see if the problem still exists

**Comment by olucurious** [comment]
@Lir10 The bug is actually not really related to this library, btw how many clients are you sending notifications to?

**Comment by Lir10** [comment]
@olucurious How come it's not related to the library ? i always to 1-5 clients ( sometimes 1 client and sometimes more) , im using twisted maybe it's related to this ?

**Comment by olucurious** [comment]
@Lir10 if you look closely at the exceptions, it coming from the request library

**Comment by Lir10** [comment]
@olucurious it does but the exception is becuase someone doesnt close the file after every request , the question is who should do it - the request library ?

**Comment by rmaciejczyk** [comment]
@Lir10 In python there is no simple way to close a file handle because that's the idea of such high level languages like Python to be separated from the system level (at least as much as they can). 

As you can see the exception comes from the request library indeed:

`response = requests.post(self.FCM_END_POINT, headers=self.request_headers(), data=payload)`

which means that it has nothing to do with pyfcm. And there is also no way to control the requests library in terms of using os resources.

In your case I would bet you are doing to many operations with file handles at the same time - you can be even not aware of it because the requests lib (or actually the urllib inside) can be used by other libraries or by a framework you use (if any) or so... Or there is too low open files limit in your os, web server etc...

Anyway I believe this is not an issue of pyfcm.

**Comment by Lir10** [comment]
Thanks for the quick answer, I also believe that it's not a problem with pyfcm I'll try to test it more to see if this issue still occures.
